environment:
  sonarqubekey:
    secure: h3llq6OeVa94hJ71UOEQSQDq75vFt+doso7iFry0gvt/fFcyeonY9wY+ETOIVITK
  global:
    PYTHONUNBUFFERED: True
    HEADLESS: 1  # For the unit tests.

version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017
install:
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      cinst msbuild-sonarqube-runner;
      cinst opencover.portable;
    }

before_build:
- cmd: py -3.5 -m pip install --user requests
- cmd: py -3.5 Tools\download_godotsharp.py
- cmd: py -3.5 RUN_THIS.py --no-prompt
- cmd: nuget restore SpaceStation14.sln
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      SonarScanner.MSBuild.exe begin /k:"ss14" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=$env:sonarqubekey" /d:"sonar.organization=space-wizards" /d:"sonar.exclusions=SFML/**" /d:sonar.cs.nunit.reportsPaths="$(Get-Location)\nunitTestResult.xml" /d:sonar.cs.opencover.reportsPaths="$(Get-Location)\coverage_report.xml";
    }

platform: x64
configuration: Debug

cache:
- packages -> **\packages.config
- Dependencies
- SS14.Client.Godot\.mono\assemblies\GodotSharp.dll

build:
  project: SpaceStation14.sln
  parallel: false
  verbosity: minimal

build_script:
- ps: msbuild SpaceStation14.sln /verbosity:minimal /nologo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Platform=x64 /p:Configuration=Debug /p:AppVeyor=yes

test_script:
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\bin\UnitTesting\SS14.UnitTesting.dll --result:nunitTestResult.xml" -output:".\coverage_report.xml";
    }
    else
    {
      nunit3-console.exe .\bin\UnitTesting\SS14.UnitTesting.dll;
    }

after_test:
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      SonarScanner.MSBuild.exe end /d:"sonar.login=$env:sonarqubekey";
    }
