language: csharp

dist: trusty
sudo: false

os:
- linux
#- osx

addons:
  apt:
    #sources:
    #- deadsnakes

    packages:
    - python3.5
    - python3-pip

cache:
  directories:
  - packages/
  - Dependencies/
  - SS14.Client.Godot/.mono/assemblies/

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
#- "pyenv versions"
#- "if [ $TRAVIS_OS_NAME = linux ]; then pyenv shell 3.6; fi"
#- "python3.6 -m pip --v"
#- "python3.6 -m pip install --user --upgrade requests"
- "python3.5 -m pip install --user requests"
- "nuget restore SpaceStation14.sln"
- "python3.5 RUN_THIS.py --no-prompt"
- "Tools/download_godotsharp.py"

script:
- "msbuild /p:Configuration=Debug /p:Platform=x64 /p:HEADLESS=1 /nologo /m /p:AllowMissingMacNatives=yes SpaceStation14.sln /p:Python=python3.5"
- "mono --debug ~/.nuget/packages/nunit.consolerunner/3.9.0/tools/nunit3-console.exe bin/UnitTesting/SS14.UnitTesting.dll"

