[package]
name = "ss14-noise"
version = "0.1.0"
authors = ["PJB3005 <pieterjan.briers+git@gmail.com>"]
publish = false

[lib]
name = "ss14_noise"
crate-type = ["dylib"]

[dependencies.noise]
git = "https://github.com/space-wizards/noise-rs.git"
branch = "develop"
default-features = false